### ISSUE TITLE
Why not JSONSchema?

### ISSUE THREAD

**Issue by n1k0** [otissv/is-schema#1]
[JSONSchema](http://json-schema.org/) seems to cover most of the use cases this lib tries to, with an ever growing tooling ecosystem around. 

Would you mind adding some rationale to the README explaining why you're proposing this alternative?

**Comment by otissv** [comment]
I've previously used [JSONSchema](http://json-schema.org/) which worked nicely but wasn't quite what I was looking for.

While  [JSONSchema](http://json-schema.org/) does indeed cover the use cases of [is-schema-valid](https://github.com/otissv/is-schema-valid) but there are unneccessary fields for my needs and  I wanted to have a schema that looked the same as an object it was for. The same way that [mongoosejs](http://mongoosejs.com/docs/guide.html) schema looks like the objects I actually write.

Also the focus was not on describing an object but only validating it.

Below is some data.

```
{
    "id"      : 1,
    "name": "A green door",
    "price" : 12.50,
    "tags"  : ["home", "green"]
}
```

This is the JSONSchema schema for the above data.

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Product",
    "description": "A product from Acme's catalog",
    "type": "object",
    "properties": {
        "id": {
            "description": "The unique identifier for a product",
            "type": "integer"
        },
        "name": {
            "description": "Name of the product",
            "type": "string"
        }
    },
    "required": ["id", "name"]
}
```

And this is the is-schema-valid schema for the above data.

```
{
    "id":  {
        type: "number",
        required: true,
   },
    "name"{
        type: "string",
        required: true,
   }
    "price": "number",
    "tags" : ["string"]
}
```

Notice the main difference is in describing the schema. In is-valid-schema there is no need for $schema, title, description or type only properties of the object. The type is always an object and as for the others these are not needed for validation. 

So it mostly comes down to a matter of style and purpose of each lib.

Will add to README.

**Comment by otissv** [comment]
It should be that difficult to add a method to also return JSONSchema but there hasn't been any requests for it.

**Comment by n1k0** [comment]
Thank you for these explanations.
