### ISSUE TITLE
could we have a runnable version without babel?

### ISSUE THREAD

**Issue by klausgao** [otissv/is-schema#2]
much thankful.

**Comment by klausgao** [comment]
I think most people still using nodejs about v4.5 .

**Comment by klausgao** [comment]
keep telling ‘isSchema is not a function’

**Comment by klausgao** [comment]
finally make it run.
need to do:
let isSchema = require('is-schema-valid').default;

**Comment by otissv** [comment]
Was just tying that. It is to do with ES6 module's export default. iF not using ES6,  require will import default as the main object and therefore will have to do isSchema.default()

I will add it to the README.

**Comment by klausgao** [comment]
@otissv thank you
