### ISSUE TITLE
bug about false and 0.

### ISSUE THREAD

**Issue by klausgao** [otissv/is-schema#4]
```
const schema = {
    isDeleted: {type: 'boolean', required: true}
};
let _obj = {
    isDeleted: false (or 0)
};
isSchema(schema)(_obj);
```

make it always fail telling the field missing.

**Comment by klausgao** [comment]
message is: Schema Required Field Error: Required field isDeleted is missing.

**Comment by otissv** [comment]
I'm out all morning (9:00 am here). Will see what's causing this in the afternoon. Think it's in the requiredValidation function as the if statement is false

**Comment by klausgao** [comment]
thank you again man

**Comment by otissv** [comment]
Should be fixed now. Required now checks for undefined instead of false value.

**Comment by klausgao** [comment]
works perfectly!!
