### ISSUE TITLE
how to set array min length?

### ISSUE THREAD

**Issue by klausgao** [otissv/is-schema#5]
I try but not working.

```
    const arrayNotEmpty = function (_arr) {
        if (_arr.length === 0) {
            return {error: 'array must not be empty.'};
        }
        return _arr;
    };

    let _objToValid = {
        tags: []
    };

    const schema = {
        tags: {type: ['string'], validation: [arrayNotEmpty]}
    };

    let _bool = isSchema(schema)(_objToValid);
```

**Comment by klausgao** [comment]
sorry to trouble you again.

**Comment by otissv** [comment]
No problem :) seems there is a bug when custom validating array as the validation function isn't being called.

**Comment by otissv** [comment]
Ok. custom validation on arrays works by mapping over the items in the array. As there are no items to check it returns { valid :true } which I think should be the correct behavior.

Therefore empty types would have to be checked via the builtin validation maybe something along the lines of

```
const schema = {
      tags: [{ type: 'string', empty: false }]
};
```

Would need to see if this api conflicts with objects within  arrays. 

Anyway is empty should be something that should be checked on all types.
I will try to get this added in the next couple of days.

**Comment by otissv** [comment]
Think it's fixed now.

All types now have builtin validation for empty properties except for booleans and nested.
Doesn't make sense to add isEmpty boolean. But will add nested support shortly.

string :  does not allow " "
`{ str: { type: 'string', empty: false } }`

number: does not allow 0
`{ num: { type: 'number', empty: false } }`

array: does not allo [].length = 0
`{ arry: { type: ['string'], empty: false }`

let me know if this throws any unexpected behavior

**Comment by klausgao** [comment]
will try soon ^_^
